# This is a part of the Makefile that generates "dqbook".
# We filched this build system from svnbook, Subversion document.

include ../tools/Makefile.base-vars
NAME = dqbook
OUTNAME = dqbook
DIR = ./book
IMAGES = $(DIR)/image/
INSTALL_DIR = ../../www
include ../tools/Makefile.base-rules
